### ISSUE TITLE
Warning: Warning: Could not determine type of attribute "templateLock"

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-gql-gutenberg#30]
With `WP_DEBUG` turned on and the below version numbers, we get these warnings when looking at the `/graphql` endpoint.

![Screen Shot 2021-12-01 at 2 23 22 PM](https://user-images.githubusercontent.com/475015/144323771-b6319343-de6b-42f2-a77c-4333b8eacb8b.png)

```
Warning: Could not determine type of attribute "templateLock" in "CoreColumnBlockAttributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreColumnBlockDeprecatedV1Attributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreGroupBlockAttributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreGroupBlockDeprecatedV1Attributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreGroupBlockDeprecatedV2Attributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreGroupBlockDeprecatedV3Attributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87

Warning: Could not determine type of attribute "templateLock" in "CoreGroupBlockDeprecatedV4Attributes" in /www/wp-content/plugins/wp-gql-gutenberg/src/Schema/Types/BlockTypes.php on line 87
{"errors":[{"message":"GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"","extensions":{"category":"request"}}],"extensions":{"debug":[{"type":"DEBUG_LOGS_INACTIVE","message":"GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."}]}}
```

**Comment by benupham** [comment]
Us too.

**Comment by nonlinearcom** [comment]
same here

**Comment by drewbaker** [comment]
@benupham Can you share with me your GQL query that caused this error? I'm not seeing it anymore (maybe fixed with new WP or WP=GQL versions?) and I'd like to try to replicate it.

**Comment by benupham** [comment]
We still get them at least on a local env (debugging is off elsewhere). 

WP 5.8.2
WP GQL 1.6.6
WP GQL Gutenberg 0.3.11

Happy to upgrade any of them if it will help. It seems to log the error regardless of the graphql query, although I haven't tried every possible combination.

**Comment by drewbaker** [comment]
Still seeing this with WP-GQL Version 1.12.2, and WP-GQL-Gutenberg Version 0.3.11

**Comment by rsm0128** [comment]
@drewbaker I created a PR #41 to fix this issue.
